### ISSUE TITLE
Ignore Files

### ISSUE THREAD

**Issue by zdavy** [NicoleCarpenter/SnowMan#1]
A `.gitignore` should be added to this project.  :smile_cat: 

For a relatively comprehensive list of the what files to ignor, and why, [check here](http://zellwk.com/blog/gitignore/)

**Comment by NicoleCarpenter** [comment]
Thank you @zachmokahn. I fixed and added files .DS_Store, Packages/ and .build/

**Comment by zdavy** [comment]
Cool, but all those files are still tracked in the repository, so you'll probably want to get them out.

**Comment by NicoleCarpenter** [comment]
Got it, thanks!

**Comment by zdavy** [comment]
Cool, but the git history also still contains the files, your should probably write them out of the history too. The easiest way would probably be squash everything down to one commit.

**Comment by zdavy** [comment]
good start for the project
