### ISSUE TITLE
Building and running tests

### ISSUE THREAD

**Issue by mnewsome** [NicoleCarpenter/SnowMan#2]
I'm a newbie to Swift.  How do I build and run the tests?

**Comment by NicoleCarpenter** [comment]
@mnewsome run `swift build`, then run `.build/debug/Specs`

**Comment by NicoleCarpenter** [comment]
@mnewsome if you want to run the application, it would be `.build/debug/Application` Application is the branch file but the author can be called whatever.

**Comment by mnewsome** [comment]
@NicoleCarpenter Thank you.  I imagine others who are new to Swift might also wonder how to build and run...and they won't likely immediately think to look at the `Issues` to find out.  These types of instructions are perfect for the `README`  :wink:
